### ISSUE TITLE
Message d'erreur lors de la création d'une annonce

### ISSUE THREAD

**Issue by PatriceF31** [duniter-gchange/gchange-client#11]
![1](https://user-images.githubusercontent.com/30532132/28995144-2e26bb38-79e1-11e7-8eb5-3464224e09ee.png)

Navigateur : Firefox 54 (Ubuntu 17.04) 54.0.1 (Window 7)
Module complémentaire : Ublock Origin, Decentraleyes (j'ai testé en deéactivant les modules, les erreurs sont similaires).
Cookie actif.

Lors de la création de l’annonce, message d'erreur : Erreur lors de l'enregristrement de l’annonce (premier screenshot)
L'annonce est néanmoins créée hier sur machine Window 7, mais pas aujourd'hui (machine Ubuntu).

Lors de la clôture d'une annonce, à nouveau un message d’erreur : Erreur lors de la clôture de l’annonce.
L'annonce est néanmoins cloturée, en s'y reprenant plusieurs fois (hier sur machine Window 7).

Lors de la modification d'une annonce : Erreur lors de l'enregristrement de l’annonce (premier screenshot)
L'annonce est néanmoins Modifiée, aujourd'hui (machine Ubuntu).

**Comment by PatriceF31** [comment]
Testé avec Chromium 59 (Ubuntu) même message d'erreur.

**Comment by blavenie** [comment]
@PatriceF31 tu n'aurais pas un plugin qui bloquerait les envois HTTP ou le javascript ?
Genre "Privacy Badger" ? Si oui, peux tu essayer en le désactivant ?

**Comment by blavenie** [comment]
ok donc a priori l'erreur exacte est : 
```
vendor-0fb156f0a3.js:11 POST https://data.gchange.fr/market/record 413 (Request Entity Too Large)
(anonymous) @ vendor-0fb156f0a3.js:11
v @ vendor-0fb156f0a3.js:11
u @ vendor-0fb156f0a3.js:11
```
confirmée par les log côté serveur : 
```
2017/08/07 10:23:46 [error] 13233#13233: *2557312 client intended to send too large body: 1679391 bytes, client: 78.225.227.66, server: data.gchange.fr, request: "POST /market/record HTTP/1.1", host: "data.gchange.fr", referrer: "https://www.gchange.fr/"
```
