### ISSUE TITLE
Incompatibilité Android 10 : gchange s'arrete systématiquement

### ISSUE THREAD

**Issue by pierrolivie** [duniter-gchange/gchange-client#118]
Sur un mobile Android (version : 10 QKQ1.190825.002) j'ai téléchargé l'app GChange sur Play Store.
Le chargement se passe bien, mais lorsque je veux la lancer je recois le message d'erreur suivant : "Gchange s’arrête systématiquement" et me propose un 'résumé' de l'erreur. Les voici :

![Screenshot_2020-02-26-15-40-18-747_com miui bugreport](https://user-images.githubusercontent.com/40866603/75442208-443f8480-595f-11ea-9e80-cfbe2a5a3e8f.jpg)
![Screenshot_2020-02-26-15-40-27-967_com miui bugreport](https://user-images.githubusercontent.com/40866603/75442222-4a356580-595f-11ea-93f7-7289bdd3d02d.jpg)

**Comment by blavenie** [comment]
Merci pour la remontée. Oui, l'API d'Android 10 a changé et l'accès au stockage sécurisé n'est plus possible de la même manière. Cesium a le même soucis.

**Comment by blavenie** [comment]
Fix in v1.2
