### ISSUE TITLE
Rétraction de la fenêtre du chat / Retraction of the chatroom window

### ISSUE THREAD

**Issue by scapharnaum** [duniter-gchange/gchange-client#121]
Il arrive souvent que la fenêtre du chat ne soit plus rétractable ; indépendamment du fait qu'elle soit épinglée ou pas !
Très gênant, car cela occulte une partie des annonces suggérées ...

**Comment by blavenie** [comment]
Si tu sais comment dompter ce chat, je suis preneur. Perso j'ai déjà eu pas mal de difficulté pour l'intégrer !

**Comment by katian** [comment]
est-ce qu'il est vraiment nécessaire ?

**Comment by scapharnaum** [comment]
@blavenie : Perso, j'ai pas encore eu le temps de jeter un oeil ! ... Cela dit, ce chat est-il vraiment nécessaire ; comme le dit @katian  ? 
À mon avis, les forums déjà existants compensent largement ce chat ...

**Comment by katian** [comment]
et il existe des solutions externes comme Relay: Chat on Every Website

**Comment by zicmama** [comment]
oui, il n'est pas très utile à mon avis...
Ce serait bien de passer par Patchwork et le protocole Scuttlebutt pour dialoguer ;)

Il existe une librairie / API nodejs
https://scuttlebot.io/apis/modules/ssb-feed.html

A ce propos, ce idéal que gchange sache lire ~/.ssb/secret.dunikey pour se connecter.

Ainsi se trouvent "facilement" connecté la place de marché et le réseau social d'amis d'amis ;)

**Comment by blavenie** [comment]
In v1.2, chatroom can be minified, and then restore as minified.
