### ISSUE TITLE
Manque : notifications par email

### ISSUE THREAD

**Issue by galuel** [duniter-gchange/gchange-client#122]
Le site serait plus utilisé encore s'il envoyait un email (standard) de notification sur plusieurs types d'alertes : 

- Quelqu'un répond à une offre qu'on a posté sur Ğchange pour prendre contact / acheter
- Une alerte sur de nouvelles offres correspondantes à des mots clés choisis (ex : je reçois un email parce qu'une nouvelle offre "hébergement en Bretagne" est apparue).

**Comment by blavenie** [comment]
> Quelqu'un répond à une offre qu'on a posté sur Ğchange pour prendre contact / acheter
Ceci est déjà fait, : Dans "Mon compte > Service en ligne > Ajouter un service / Type EMAIL"

 > Une alerte sur de nouvelles offres correspondantes à des mots clés choisis (ex : je reçois un email parce qu'une nouvelle offre "hébergement en Bretagne" est apparue).

Cela est effectivement à réaliser.

**Comment by zicmama** [comment]
> Une alerte sur de nouvelles offres correspondantes à des mots clés choisis

Cette fonctionnalité est déjà prête depuis 6 mois dans G1sms ;)
https://git.p2p.legal/axiom-team/G1sms/src/master/shell/cron_GCHANGE.sh

Pour bien l'intégrer il faudrait arriver à utiliser l'API des Pods G+ pour envoyer des messages en batch. Question posée maintes fois, sans réponse...

**Comment by blavenie** [comment]
Salut @zicmama 

> Pour bien l'intégrer il faudrait arriver à utiliser l'API des Pods G+ pour envoyer des messages en batch. Question posée maintes fois, sans réponse...

Excuses moi, je pensais l'avoir fait.
Pour enovyer des messages sur un Pod Gchange ou Cesium+, il faut : 
 - construire un JSON signé ([cf doc API](https://git.duniter.org/clients/cesium-grp/cesium-plus-pod/-/blob/master/src/site/markdown/REST_API.md#data-document)), avec les champs nécessaire de `message/inbox` (cf [DOC](https://git.duniter.org/clients/cesium-grp/cesium-plus-pod/-/blob/master/src/site/markdown/REST_API.md#messageinbox))
 - envoyer le docuemtn JSON en POST, à `<URL_POD>/message/inbox`

Attention, le `issuer` doit aussi avoir un profile gchange (`<URL_POD>/user/profile`)

Redis moi si pb
