### ISSUE TITLE
L'application crash à l'ouverture

### ISSUE THREAD

**Issue by yann1108** [duniter-gchange/gchange-client#130]
Depuis au moins 2 mois l’application crash au démarrage sous Android :
Android 10, One UI 2.1, (mise à jour 1 avril 2020) (Samsung A51)

J'ai désinstaller et ré-installer pour voir si mon fichier apk était corrompu,
depuis Google play et en direct sur Github - idem.

![Screenshot_20200703_One UI Home](https://user-images.githubusercontent.com/272091/86417176-8ccfcb80-bccc-11ea-841c-95e48b17b6f4.jpg)

peut-être la mise à jour ? latest release 13 mars vs Samsung au 1er Avril

**Comment by blavenie** [comment]
Oui, c'est un bug d'Android 10, lié à l'écran de verrouillage de la page d'accueil.
Il faut essayer avec ou sans verrouillage, et l'un des 2 mode dévrait fonctionner.

Ca sera corriger dans la prochaine version.

**Comment by yann1108** [comment]
Dans mon cas, les 2 modes aboutissent au même crash,
impossibilité d'ouvrir l'application.

Tester aussi les autorisations de l'app. (Photos & Stockage) = idem

----------------------------------------------------------------------------------------
Question, qui n'a rien à voir :
entre 2 certifications données 
- l'une parmi 5 pour un nouveau (toutes disponibles)
- l'une envers un "ancien" certifié
Laquelle passe en premier ? (date d'émission ?)

**Comment by blavenie** [comment]
Fix. Now using cordova-plugin-secure-storage-android10 v6.0.4 or 6.0.5
