### ISSUE TITLE
Contact vers une personne qui n'a pas configuré sa clé publique

### ISSUE THREAD

**Issue by scanlegentil** [duniter-gchange/gchange-client#142]
Lorsqu'un utilisateur qui a posé son annonce n'a pas configuré sa clé publique, le lien vers son profil renvoie vers "https://www.gchange.fr/#/app/wot//"  (forcément, il manque la clé entre les deux derniers //)   .  Par défaut cette url renvoie vers son propre profil Cesium+ / WoT . Du coup ça donne l'impression que ça bug.

D'ailleurs l'url contient le mot WoT mais la clé publique d'un annonceur n'est pas forcément WoT membre (mais je pinaille :)  

En outre, après avoir cliqué sur le bouton "écrire un message" , le client de messagerie nous laisse le saisir, mais au moment d'envoyer le message , le destinataire saisi par défaut automatiquement n'a pas de clé pour le chiffrement, et on reçoit le code erreur "Erreur - Erreur lors de l'envoi du message. - Un destinataire est obligatoire pour le chiffrement."  .  Pour l'utilisateur final, qui ne comprend pas ce défaut de clé publique de l'annonceur, ce message n'est pas clair. 

2 propositions: 
- soit interdire les annonces sans clé publique . Je pense que c'est la meilleure mauvaise idée car elle simplifie la gestion de l'erreur potentielle. 
- soit empêcher la possibilité d'écrire ou de cliquer sur le profil d'un profil qui n'a pas mis sa clé publique (dans les annonces et dans les commentaires). Ou renvoyer vers une page qui dit "cet utilisateur n'a pas configuré sa clé publique G1 et son identité ne peut donc pas être retrouvé sur la blockchain" . Ca pourrait être aussi instructif pour les gens.

**Comment by zicmama** [comment]
- soit révéler qu'un compte gchange est également un compte cesium (ce sont les même clefs)

**Comment by blavenie** [comment]
Bizarre, peux tu me donner le lien de l'annonce ?
Logiquement le lien vers le compte gchange utilise la clef publique Gchange, et non celle de sont compte G1.
Or les Pod n'accepte pas les annonces s'il n'y a pas de profile Gchange de saisi.

C'est peut-etre un cas de personne qui ont supprimé leur compte, après avoir posté une annonce.
Pour le moment, les annonces ne doivent pas etre supprimées, mais elle ne se réplique alors plus sur le réseau P2P

**Comment by blavenie** [comment]
> D'ailleurs l'url contient le mot WoT mais la clé publique d'un annonceur n'est pas forcément WoT membre (mais je pinaille :)

Non effectivement il faudra que je renomme cela en ~/app/user par exemple.

**Comment by blavenie** [comment]
Fait en 1.2.7
