### ISSUE TITLE
Clé publique différente de celle de l'utilisateur non prise en compte

### ISSUE THREAD

**Issue by JulienRennes** [duniter-gchange/gchange-client#146]
Bonjour,

lorsque l'on renseigne une clé publique dans le corps de l'annonce qui est différente de notre compte, celle-ci n'apparait pas correctement dans l'annonce qui donne la clé publique du compte et ne prend pas en compte la clé fournie lors de la création de l'annonce.
Exemple pour ce crowdfunding: [là](https://www.gchange.fr/#/app/market/view/AXTpMdU8RPsuHHWVrua1/valorisation-dordis-famillescoles-pc-n18)

Merci pour votre travail!

Julien

**Comment by blavenie** [comment]
j'ai pu corriger cette anomalie. Merci !
J'ai ajouté une note à ton annonce, pour expliquer comment contourner.
