### ISSUE TITLE
Message intempestif à la création d'une annonce

### ISSUE THREAD

**Issue by Vivakvo** [duniter-gchange/gchange-client#152]
Bonjour,

Depuis plusieurs mois, un message intempestif (non bloquant) s'affiche lors de la création d'une annonce (sur www.gchange.fr) : 
![image](https://user-images.githubusercontent.com/37816591/102653762-bc399e00-416f-11eb-9cb5-f4ef5872e755.png)

Serait-il possible de corriger cela ?

Merci d'avance

**Comment by blavenie** [comment]
Normalement, c'est corrigé depuis la v1.2.5, tu confirmes ?

**Comment by blavenie** [comment]
Ah non effectivement, je viens de le reproduire !

**Comment by blavenie** [comment]
fix in 1.2.6
