### ISSUE TITLE
La rubrique "Ceci pourrait vous intéresser" propose nos propres annonces ;)

### ISSUE THREAD

**Issue by vtexier** [duniter-gchange/gchange-client#155]
La rubrique "Ceci pourrait vous intéresser" propose nos propres annonces ;)

Il ne faudrait pas avoir nos propres annonces dans les annonces qui peuvent nous intéresser...

**Comment by blavenie** [comment]
Je penses que c'est corrigé depuis, non ?

**Comment by vtexier** [comment]
Heu... Non, il me conseille encore mes propre annonces ;)

![Capture du 2021-02-28 18-39-21](https://user-images.githubusercontent.com/2174016/109427836-79f4ce80-79f4-11eb-9bbd-3e6c41bbe89b.png)
