### ISSUE TITLE
Nom du vendeur

### ISSUE THREAD

**Issue by vincentux** [duniter-gchange/gchange-client#17]
Est-il possible d'ajouter le nom du vendeur sur la [première page des annonces](https://www.gchange.fr/#/app/market/lg) ?

![gchange_nom](https://user-images.githubusercontent.com/11737560/29173729-866f5546-7de4-11e7-8537-47f503a0a269.png)

**Comment by blavenie** [comment]
Oui, j'ay avais pensé, merci de ma rappeller !
