### ISSUE TITLE
Connexion gchange

### ISSUE THREAD

**Issue by Clinerode** [duniter-gchange/gchange-client#174]
Bonjour je n'arrive pas a me connecter avec le noeud data.gchange.fr ca me met serveur indisponible et je ne trouve pas d'autres noeuds pour me connecter dans l'application. Ma version est 1.2.8 et j'utilise Android sur 1 xiaomi note 9.
Merci pour votre aide.

**Comment by blavenie** [comment]
Voila c'est corrigé. Dans la version 1.3.0, la sélection du noeud se fera automatiquement, en cas de défaillance. Merci !

**Comment by Clinerode** [comment]
Super
Merci beaucoup

Le sam. 19 juin 2021 à 16:06, Benoit Lavenier ***@***.***> a
écrit :
