### ISSUE TITLE
Modifier une annonce

### ISSUE THREAD

**Issue by c-geek** [duniter-gchange/gchange-client#18]
Dans "Mes annonces", quand on clique sur le bouton « Modifier » pour modifier une annonce, celle-ci tente de se charger puis on tombe sur une erreur : 

![image](https://user-images.githubusercontent.com/969136/29231539-e4f4efdc-7ee7-11e7-9af8-2c81fe2cdcbe.png)

Voici la sortie console JS : 

![image](https://user-images.githubusercontent.com/969136/29231553-f2e99e80-7ee7-11e7-9d60-9c86fc0af4f9.png)

**Comment by blavenie** [comment]
Modification apportée en 0.5.5 : augmenter le timeout (config.js) à 30s, sur le serveur de prod.

> kimamila: cgeek, dis moi, tu as toujours ton soucis de modification d'une annonce gchange  ?
> cgeek: c'est mieux là, je n'ai pas eu de bug
