### ISSUE TITLE
"afficher l'application en plein écran"

### ISSUE THREAD

**Issue by farvardin** [duniter-gchange/gchange-client#184]
bonjour,

à chaque fois que je vais sur le site gchange depuis le navigateur firefox sur mon mobile, ça met un pop up "afficher l'application en plein écran", avec incitation pour cliquer sur "oui". Je ne souhaite absolument jamais l'afficher ainsi (parce que c'est pénible pour passer sur un autre onglet ensuite et que je n'en ai pas l'utilité, mon écran est suffisamment grand).

Dans les paramètres j'ai bien "activer le stockage local" et "conserver les données de navigation", mais invariablement cela s'affiche à chaque connexion. 

![image](https://user-images.githubusercontent.com/477243/134807994-f114b96a-456b-42da-a911-fa9acebe186d.png)

Peut-être qu'une option dans les paramètres pour désactiver cela serait pratique (d'autres personnes m'ont signalées que ce pop up les énervait un peu)

**Comment by blavenie** [comment]
ok, oui, il faudrait que je retire cette fonction, qui est assez casse pied. Surtout pour les grand écran.
