### ISSUE TITLE
Enlever les mentions sur le logiciel Sakia

### ISSUE THREAD

**Issue by yann1108** [duniter-gchange/gchange-client#187]
Comme le logiciel SAKIA n'est plus maintenu, il ne faudrait pas le mentionner dans les aides à utilisation, "à propos" et autres,
à moins de vouloir motiver un développeur a en reprendre le développement
![Capture du 2021-10-23 00-22-57](https://user-images.githubusercontent.com/272091/138529474-8e71cc33-15c3-4e7d-a608-46e2841684f0.png)
.

**Comment by blavenie** [comment]
done in 1.4.1
