### ISSUE TITLE
problème applications mobiles

### ISSUE THREAD

**Issue by Rajesh03190** [duniter-gchange/gchange-client#189]
Bonjour
sur l'application GChange, je n'arrive pas à publier des annonces pour faire de la vente, ni pour les services. j'ai un iPhone, j'ai essayé sur un androïd et c'est le même constat. j'ai pu démarrer et faire un essai sur mon PC de travail.
j'ai aussi un compte Cesium, mais je ne suis pas encore membre... je ne sais pas si le problème est du au faite que je ne suis pas encore membre.
mon compte : "Rajesh03190"
merci à vous. bonne journée

Rajesh

**Comment by blavenie** [comment]
Je penses qu'a cette date le site devait etre en rade... a doit fonctionner mieux maintenant.
