### ISSUE TITLE
Connexion via un compte g1

### ISSUE THREAD

**Issue by Cywil23** [duniter-gchange/gchange-client#19]
Bonjour,

Merci beaucoup aux développeurs pour cette superbe plateforme ! Toutefois j'y rencontre un petit soucis...

J'ai un compte g1 qui fonctionne très bien mais quand j'essaye de me connecter sur gchange avec ces mêmes identifiants, ça ne fonctionne pas.

C'est normal et il faut que je me crée un autre compte sur gchange ou c'est un bug ?

Merci d'avance pour votre retour

Cyril

**Comment by blavenie** [comment]
Oui, en fait pour le moment j'ai pris le parti de demander une création de compte **différent** pour gchange.
Ceci est motivé par le fait qu'une plateforme d'annonce a moins besoin d'être sécurisé qu'un portefeuille de monnaie. Il vaut mieux, donc, NE PAS utiliser son compte G1 membre.

toute fois, pour utiliser un compte G1 "simple portefeuille", tu peux "créer un compte" gchange et remettre les même identifiants.

(je sais pas si je suis très clair, là...)
