### ISSUE TITLE
Annonces favorites

### ISSUE THREAD

**Issue by info73fr** [duniter-gchange/gchange-client#192]
Bjr,
Cela fait plusieurs semaines que je marque des annonces comme favorites mais que la liste ne se met pas à jour...
Si ça peut aider, mon compte est 'Ju73', merci d'avance.

**Comment by blavenie** [comment]
il manque peut-etre le chargement des dernieres. Avez vous essayer de changer l'ordre de tri ?

**Comment by blavenie** [comment]
Duplicate #186

**Comment by info73fr** [comment]
Non, malheureusement ça ne change rien. Peut-être est-ce 1 pb lié à mon
compte et non général, ds ce k, veuillez réinitialiser/nettoyer les données
de mon compte, car c très bloquant, merci d'avance^^


Le jeu. 25 août 2022 à 16:36, Benoit Lavenier ***@***.***> a
écrit :

> il manque peut-etre le chargement des dernieres. Avez vous essayer de
> changer l'ordre de tri ?Message ID:
> ***@***.***>
>
