### ISSUE TITLE
demande pour un probleme

### ISSUE THREAD

**Issue by Alicedusud** [duniter-gchange/gchange-client#195]
bonjour

j'ai un compte gchange
j'y ai mis des annonces et reçu des messages
quand je reçois le mail qui me dit que j'ai des notifications sur gchange la clé publique ne correspond pas à la mienne et je me suis apercu qu'il y a des messages que je n'ai pas reçu car ils arrive sur cette clé différente
j'ai du faire une erreur quelque par et j'ignore où
pouvez m'aider svp ?
merci
bien à vous

**Comment by blavenie** [comment]
Non, en fait la clef affichée dans le message est celle de votre gchange, qui est masquée.
Iil ne s'agit pas de votre clef publique de compte G1. Seulement de votre compte Gchange.
Les deux comptes sont dissocié, bien que vous pouvez indiquer votre clef G1 dans votre profil Gchange.

J'espère que cela réponds à vos questions

**Comment by Alicedusud** [comment]
Bonsoir monsieur merci de votre réponse mais non il y a autre chose qui ne
va pas parce que je reçois des notifications avec une clé dont je ne peux
pas ouvrir le compte en fait je vais ouvrir un compte et supprimer celui-là
quand j'aurai transférer les annonces voilà je vais faire au plus simple
même si c'est compliqué beaucoup de travail finalement ce système est quand
même très difficile je vous remercie beaucoup en tout cas bonne soirée

Le jeu. 25 août 2022 à 16:39, Benoit Lavenier ***@***.***> a
écrit :
