### ISSUE TITLE
photo requirements for Ads?

### ISSUE THREAD

**Issue by kaipie9** [duniter-gchange/gchange-client#196]
hello, all resolved

**Comment by blavenie** [comment]
Gchange scale pictures, to be able to sent it as base64 string.
This is required to have a full ElasticSearch (ES) storage. The version of ES is quite old (v2.4).
We need to complete rewrite the CHange Pod, to a new version of ES, to be able to store binaries, like pictures

**Comment by kaipie9** [comment]
ok. thanks benoit.
i got a bit of support on the duniter forum too, posing the same query.

but nice to hear back from you, and to know things are changing on the software front, for more efficient, effective functioning..

wondered if you had any clear advice on photo sizes/resolutions that gchange will likely accept? as i plan to take some photos soon with my phone, so can edit the settings to suit.

i heard on duniter forum, that 1000x1000 px was recommended? any other input appreciated. thanks
