### ISSUE TITLE
Rafraîchissement du courrier

### ISSUE THREAD

**Issue by c-geek** [duniter-gchange/gchange-client#22]
J'attendais un message personnel pour mon annonce Bitcoin, et je ne voyais pas l'icône de mail afficher une petite icône supplémentaire m'indiquant l'arrivée d'un message.

Au bout d'une journée, je me décide à rafraîchir la page : cette fois l'icône m'indique qu'un nouveau message m'est parvenu.

Peut-être qu'une amélioration consisterait à rafraîchir, par exemple toutes les 5 minutes, le contenu de la boite mail ?

**Comment by blavenie** [comment]
Oui, d'une manière générale, je penses qu'il y a des soupures des WebSockets, dans les navigateurs.
Le problème est le même par exemple dans la vue réseau de Cesium.

Je ne sais pas pourquoi les WebSocket se coupent (sans message d'erreur !)...

**Comment by c-geek** [comment]
Visiblement ce n'est pas une erreur, simplement il y a mille raisons que ça arrive. Par exemple moi je mets très souvent mes machines en hibernation, ce qui coupe le WebSocket.

Il y a des solutions, notamment écouter l'événement "onclose" : https://stackoverflow.com/a/28932266

**Comment by c-geek** [comment]
Et aussi, ne pas oublier la bonne configuration Nginx pour les timeouts de WebSocket :

    # WSS 
    proxy_http_version 1.1;  
    proxy_set_header Upgrade $http_upgrade;  
    proxy_set_header Connection "upgrade";  
    proxy_read_timeout 86400s;  
    proxy_send_timeout 86400s;

**Comment by blavenie** [comment]
> Et aussi, ne pas oublier la bonne configuration Nginx pour les timeouts de WebSocket :

ah yes, merci !!

**Comment by c-geek** [comment]
> En mettant un log dans onclose() de mes websockets (Cesium), j'ai l'impression d'avoir :
>
> 1min pour /ws/block
> 4min pour /ws/peer

Pas du tout, je n'ai mis aucun timeout particulier. D'ailleurs le code de cette librairie ne mentionne aucun timeout non plus :confused: 

> hé mais ca fait pas trop quand même, 24h ?

C'est sur mon serveur, ça ira.
