### ISSUE TITLE
Recherche avancée par département

### ISSUE THREAD

**Issue by yann1108** [duniter-gchange/gchange-client#33]
il est souvent plus judicieux de permettre une recherche par département que simplement par localité. (rendre disponible les deux)
En effet par exemple, nous avons plus d'annonces (et le chiffre va croître car nous faisons une publicité acharnée pour le site ḡChange.fr sur l'Occitanie)
mais beaucoup n'habite pas à Toulouse même, et chercher localité par localité est fastidieux.
Une recherche avancée qui peut être faîte par les 2 premiers chiffres d'un département serait pratique. (demandant à tous de le préciser)

**Comment by blavenie** [comment]
Bonjour @yann1108 !
Merci beaucoup pour cette bonne idée.
Savoir que cette fonction est attendue me donne aussi du courage, pour prendre le temps de faire ces développements.

Si tout va bien, je m'y attèle la semaine prochaine.

**Comment by blavenie** [comment]
Recherche spatiale implémentée, à partir d'une ville et aux alentours : v0.6.3
