### ISSUE TITLE
Clic droit sur annonces

### ISSUE THREAD

**Issue by LeoBoudet** [duniter-gchange/gchange-client#35]
Un clic droit sur une annonce visible sur la place de marché nous emmène directement sur le détail de celle-ci. Ce n'est pas très commode lorsque l'on souhaite ouvrir plusieurs onglets tout en gardant l'onglet de la place de marché ouvert.
À moins qu'il y ait une raison pour cela, dans ma manière de naviguer c'est un peu gênant...

**Comment by Zatalyz** [comment]
Je renchéris, j'apprécierais vraiment que ce comportement du clic droit change :) 
J'aime bien ouvrir plusieurs onglets avec les diverses annonces sur d'autres sites de petites annonces, car cela permet de comparer des annonces similaires. Ne pas pouvoir le faire sur gchange est un peu gênant, ça rend la navigation plus laborieuse.

**Comment by blavenie** [comment]
@Zatalyz @LeoBoudet avez-vous tester le comportement sur la dernière version ?  https://forum.monnaie-libre.fr/t/gchange-nouvelle-version-0-6-5-beta/1331

Le clic n'est pas toujours présent, mais au moins le clic gauche ouvre dans une nouvel onglet.

**Comment by LeoBoudet** [comment]
Pour moi, l'aspect le plus gênant concerne les annonces elles-mêmes.
En revanche, dans la nouvelle version, un clic sur un lien ne me l'ouvre pas dans un nouvel onglet comme tu dis mais ouvre simplement une "bulle" qui redonne le lien sélectionné (à l'instar des clés publiques sous Cesium).
(Navigateur Firefox à jour.)

**Comment by blavenie** [comment]
Corrigé en v0.7.4
