### ISSUE TITLE
Probleme de connexion à mes message

### ISSUE THREAD

**Issue by wiloka0** [duniter-gchange/gchange-client#39]
Salut

Je me connecte normalement sur mon compte. J essai de lire un message et j ai deux messages d'erreur succéssif. 

1 : Erreur
Erreur lors de la récupération du message.
Resource not found (https://data.gchange.fr/message/inbox/[object Object])

2 : Erreur
Lecture du message impossible.
Vous n'êtes pas le destinataire de ce message : déchiffrement impossible.

c'est bien mon compte, mon mdp , et bien à moi qu 'il est adressé. 

Que se passe t'il ?

**Comment by blavenie** [comment]
Corrigé en v0.6.3
