### ISSUE TITLE
Confusion entre compte "annonce" et compte porte-feuille

### ISSUE THREAD

**Issue by yann1108** [duniter-gchange/gchange-client#41]
Bonjour Benoît,
Je soulève ici un problème fondamental de concept et donc de sécurité avec GChange.

si j'ai bien compris (car cela n'est pas clair pour beaucoup de gens en arrivant sur GChange)
- l'ouverture d'un compte sur GChange.fr correspond soit : 
1) à la création d'un compte porte-feuille dans la blockchain
2) à l'utilisation des logins d'un compte existant dans la blockchain (porte-feuille, ou membre TdC)

C'est un point qui est confus et pas compris par la grande majorité des gens (même des anciens de la Ǧ1) - On vient sur GChange pour les annonces et on pense, ouvrir un simple compte d'annonce.

Il y a plusieurs problèmes (si je ne me suis pas trompé sur le fonctionnement)
1) la confusion entre les types de compte
2) l'accès direct aux "comptes en banque" via une base de données centralisée 

(Je pense que les logins de "compte en banque" Ǧ1 sont toujours stockée dans la blockchain)
mais ça augmente la possibilité de captage des logins (si je comprends bien)

Les comptes GChange devraient être totalement indépendants de la blockchain et en aucun cas, être des "comptes en banque" - ce que la plupart des gens, je pense, ne réalisent pas.

**Comment by vtexier** [comment]
@yann1108 : j'ai eu la même confusion.

Je suis d'accord, il faut une documentation et un message explicite à la création du compte.

Mais en fait, RIEN n'est stocké dans la blockchain Duniter lorsque tu crées un compte Ğchange. La clef publique de ce compte est stockée sur le pod Ğchange (elasticSearch) avec ton profil. C'est tout.
Rien n'est stocké dans la blockchain Duniter.

Par contre, ce compte est "compatible" avec Duniter.
Tu peux t'en servir de portefeuille simple Ğ1 dans Sakia ou Cesium.

Mais, là encore, la clef publique n'est écrite dans la blockchain Duniter que si elle est liée à une identité pour en faire un compte membre (ce n'est pas le cas ici) ou si une transaction l'utilise. Comme pour tous les comptes Duniter.

Que @blavenie me corrige si je dit une bêtise...

**Comment by Olm-e** [comment]
hello,
je renchérit sur cette issue qui me semble fort problématique : la confusion est totale parce qu'il n'y a aps de doc expliquant cette différence, ce qui ammène même à des problème du genre : Mr Truc s'inscrit en suivant les instructions, et annonce la vente de chose, Mme Brol achète et paye sur l'adresse indiquée, et Mr Truc ne "reçoit pas la monnaie" parce qu'il n'a pas compris que cette adresse d'inscription était aussi un compte...  
La page d'aide se doit de mentionner cette énorme subtilité ;)
je peut voir à faire une PR si besoin, mais je penses que les devs actuels formuleront ça bien mieux connaissant les détails ... 
merci !!

**Comment by Insoleet** [comment]
Sur le même sujet, on a eu une discussion avec aeris : https://social.imirhil.fr/@aeris/99654561657081978

Je pense qu'il faut complètement revoir l'UI de gchange au niveau de la gestion des clés. Actuellement c'est vraiment dangereux (je n'ose imaginer le nombre d'utilisateurs qui font n'importe quoi car l'UI n'est pas claire !)
