### ISSUE TITLE
Création d'un forum et d'un salon de discussion dédié

### ISSUE THREAD

**Issue by vtexier** [duniter-gchange/gchange-client#42]
Ğchange prends de l'ampleur et les utilisateurs n'ont que les forums Duniter pour s'exprimer.

Cela "pollue" un peu les forums. Voir https://forum.duniter.org/t/g1change-impossibilite-de-se-connecter-le-30-12-17/3885/5

Je suggère de créer un salon de discussion XMPP (sur movim par exemple).
C'est rapide. Et pourquoi pas un "Groupe" Ğchange  sur Movim.

En attendant un salon Discourse dédié...

**Comment by blavenie** [comment]
oui, bonne idée.
Tu sais faire pour Movim ?

**Comment by vtexier** [comment]
Ben en fait non, je me suis un peu emballé, pas depuis l'interface ;-)

Il faut que je creuse la question, mais on dirait qu'il faut installer un serveur XMPP avec des extensions, pour créer des salons de discussions. Puis certainement un serveur movim. Avant de pouvoir créer des "serveurs de communautés".
Pas si simple donc.

Je vais chercher plus d'infos...

**Comment by blavenie** [comment]
un salon XMPP comme pour duniter.org serait peut-etre plus simple.
Sais tu qui l'a monté sur Duniter ? @c-geek ?

**Comment by vtexier** [comment]
Je crois que c'est Moul.

**Comment by blavenie** [comment]
Fait ! =>  https://forum.gchange.fr 
et chat intégré à la version 0.7.x
