### ISSUE TITLE
2 problèmes

### ISSUE THREAD

**Issue by tcrouzet** [duniter-gchange/gchange-client#43]
Salut
Et bonne année

2 problèmes

1. Le plus gros, des membres vendent des ebooks piratés, ça fait désordre.
Pas le meilleur moyen de donner une bonne image de G1

2. Quand j'ai créé mon compte gchange, une clé publique m'a été attribué.
Un membre m'a fait un virement sur ce compte.
Pourquoi je ne peux pas associer la clé de mon compte principal?
Et comment j'accède à ce compte?

**Comment by blavenie** [comment]
> Le plus gros, des membres vendent des ebooks piratés, ça fait désordre.
Pour ca, il faut qu'on ajout des fonctions de modérations, mais ce n'est pas si simple en P2P.
Ce que j'envisage c'est d'avoir une système de "Like" qui fait monté un compteur. Dans les options de recherche, les gens pourront choisir leur niveau de sélection.

> Pas le meilleur moyen de donner une bonne image de G1
Stéphane te dirait que la G1 n'a rien à voir avec gchange. Je suis assez d'accord.
j'ai fait gchange pour dépanner la communauté, ici en Mayenne. Si ca sert à d'autres tant mieux mais c'était pas forcément le but.
Bref, ca avance à petit pas, mais dans le sens P2P (donc dans le bon sens ?)

> Quand j'ai créé mon compte gchange, une clé publique m'a été attribué.
> Un membre m'a fait un virement sur ce compte.
> Pourquoi je ne peux pas associer la clé de mon compte principal?
Oui, l'association de compte est fonction en cours de développement.
Mais ca touche plusieurs outils (dont Cesium). 

> Et comment j'accède à ce compte?
 Il suffit de rentrer tes identifiants Gchange dans un logiciel client de la G1 (Sakia ou Cesium).
Tu pourras ensuite faire le virement vers ton compte principal.
