### ISSUE TITLE
Création de compte et authentification > Différence de visibilité de l'identifiant secret

### ISSUE THREAD

**Issue by Paypay77** [duniter-gchange/gchange-client#44]
Bonjour, 
je note des différences sur l'authentification entre Cesium et gchange. 
Au préalable, est ce que les identifiants et Mots de pass de Cesium doivent être utilisé sur gchange afin de linker les comptes pour le paiement en G1 ? Ou separe t'on les comptes et dans nos annonce on fait référence à notre Clef publique pour etre payé ? 

Dans tous les cas,  le fait que mon identifiant secret apparaisse en "claire" lors de l'ouverture de session : Connexion ( et non pas de l'inscription) est clairement gênant . Ce doit être un oublie vu que c'est bien caché lors de l'inscription

amicalement, 
Paÿpaÿ

**Comment by blavenie** [comment]
Il ne faut pas utiliser son compte G1 membre pour se connecter à gchange.

A partir de la, il n'est pas si important d'avoir un identifiant visible.

Cela dit, c'est sur qu'il vaudrait mieux que ce soit cohérent, entre l'inscription et la connection.
Je vais corriger cela, mais je ne sais pas trop encore dans quel sens...

**Comment by Nartagnan** [comment]
Si je peux donner mon avis, je conseille de faire comme sur Cesium : l'identifiant doit être secret, que le compte soit membre ou pas. Ça a l'avantage de la clarté, et c'est pédagogique.

**Comment by pierrolivie** [comment]
"Il ne faut pas utiliser son compte G1 membre pour se connecter à gchange."

Comme ce n'est pas très clair pour le débutant et qu'à lire le forum je ne suis pas seul dans ce cas, il faudrait, une fois l'erreur faite pouvoir détruire son compte Gchange pour en recréer un indépendant de son compte Ğ1 membre. Je n'ai pas trouvé le moyen de le faire.

**Comment by Nartagnan** [comment]
Serait-il possible de "transférer" son compte Ğchange à une novuelle clef ? (toutes les infos spécifiques à Ğchange) ? Ou bien est-ce techniquement indissociable ?

**Comment by blavenie** [comment]
> Y a-t-il (y aura-t-il) un moyen de **détruire** son compte gchange ou d'en modifier la clé ?
> Je ne m'en sert plus pour raison de sécurité énoncé par blavenie "_Il ne faut pas utiliser son compte G1 membre pour se connecter à gchange._"

Bonne idée d'ajout de fonctionnalité. Peux tu créé un nouveau ticket (issue) pour cela stp ?

**Comment by blavenie** [comment]
En v0.9.1, la création de compte Gchange a été clarifié, pour être homogène avec le fenetre de connexion.
