### ISSUE TITLE
Messages d'erreur pour lire les messages envoyés sur Gchange

### ISSUE THREAD

**Issue by Dom71** [duniter-gchange/gchange-client#45]
Lorsque j’ouvre ma messagerie Gchange et que je tente de consulter un message envoyé
une première fenêtre d’erreur apparait, lorsque je la valide, une seconde apparait mais je n’ai pas
accès au corps de mes message envoyés.
Le texte du second message est correct puisque je veux lire un message que j’ai envoyé.
message erreur1
message erreur2

normal ? pas normal ? quoi faire ?
Remerciements
Dom

**Comment by blavenie** [comment]
Peux tu me dire quelle version de gchange tu utilises ?
c'est l'App Android ? la version web ?

S'agit il de messages anciens ? (quels est leur date).

Merci de votre aide !!

**Comment by Dom71** [comment]
Bonsoir Benoit Voilà les infos utiles, version pc
Cordialement
Dom.

change v0.6.4
date : 2017-12-04T16:03:38.043Z
Application libre (licence GNU GPLv3).
Code source :
https://github.com/duniter-gchange/gchange-client
Développé par :
Benoit Lavenier
Avertissement
Cette application n'est pas encore stabilisée (développement en cours).
N'hésitez pas à nous remonter les anomalies rencontrées !
Remonter un problème
