### ISSUE TITLE
[dev] ionic serve cannot find module internal/util/types

### ISSUE THREAD

**Issue by vindarel** [duniter-gchange/gchange-client#49]
Hi,

I'm trying to install and run this locally. With `ionic serve`, I get:

```
$ npm start                                                    *[master] 

> gchange-client@0.6.5 start /home/vince/bacasable/gchange-client
> ionic serve


Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/home/vince/bacasable/gchange-client/node_modules/ionic/node_modules/ionic-app-lib/)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)

Cannot find module 'internal/util/types' (CLI v1.7.16)

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
8.0.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Distributor ID:	LinuxMint Description:	LMDE 2 Betsy 
Node Version: v9.3.0
```

looking at https://github.com/remy/nodemon/issues/1124 and https://stackoverflow.com/questions/40308623/cannot-find-module-internal-fs-after-upgrading-to-node-7/40406482#40406482 and https://github.com/npm/npm/issues/19032 I tried

- installing the latest ionic (install -g ionic@latest)
- deleting npm cache and reinstalling with yarn
- `yarn add graceful-fs@latest` (didn't even check if it's used)

Any more ideas ? Regards.

Note that I didn't change the `app/config.json` (I don't understant what it's for yet).

**Comment by blavenie** [comment]
Do you use nodejs in version 5.x ? 

To install it : 
- install nvm tools
 - then run : `nvm install 5`
 - then : `npm install -g gulp bower@1.8.0 cordova@6.5.0 ionic@1.7.16`
 - `npm install`

**Comment by vindarel** [comment]
Thanks, I missed the node version.
