### ISSUE TITLE
Ajout de catégorie

### ISSUE THREAD

**Issue by vincentux** [duniter-gchange/gchange-client#5]
Pourra t'on ajouter des catégorie ou pas dans les annonces ?
Sinon je veux bien une catégorie "**Vêtement et accessoire**" merci ;)

et sinon voici la liste des catégorie sur le bon coin (_tu dois surement la connaitre_) : 

![categorie_lbc](https://user-images.githubusercontent.com/11737560/27124222-a119e15c-50f0-11e7-8b3b-8f3edf95e243.PNG)

**Comment by blavenie** [comment]
Hello @vincentux !
merci du retour !

Attention, pour le moment gchange sert à une expérimentation, dans un vidé grenier. l'appli que tu as testé n'est pas encore prete pour la G1 ;(

mais j'y travaille.

Je posterai sur le chat+forum quand j'aurais quelque chose à tester vraiment
