### ISSUE TITLE
Interface messageries gchange et cesium/g1.duniter bientôt opérationelle ?

### ISSUE THREAD

**Issue by DYves** [duniter-gchange/gchange-client#51]
Mes tests de messages entre clefs publiques gchange et cesium ne fonctionnent pas entre les deux sites alors qu'en interne sous Cesium si.

**Comment by blavenie** [comment]
Bonjour @DYves,
je ne suis pas sûr de comprendre.
Vous souhaitez utiliser Gchange pour envoyer des messages qui arriveraient sur Cesium+ ?

Ğchange utilise un réseau de noeuds de données (`gchange-pod`) différent de celui utilisé pour les données de Cesium+ (profiles, messages privées, etc.).
Il n'y a pas de connexion entre les deux.

Les seuls point communs entre Cesium et Ğchange, sont : 
 - Utilisation du symbole monétaire Ğ1 pour les montants
 - Utilisation des même principe de chiffrement par clefs publique/secrète
 - Utilisation d'un framwork de développement d'interface Web et mobile (Ionic Framework)
 - Utilisation d'ElasticSearch pour le stockage des données hors BlockChain. Le stockage physique des données est en revanche différent.

**Comment by DYves** [comment]
Merci pour ces éclaircissements Benoît,
il n'y a donc pas attendre un tel interfaçage,
Bravo pour l'initiative gchange en tous cas :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
