### ISSUE TITLE
Confusion sur les clés

### ISSUE THREAD

**Issue by dmilly31** [duniter-gchange/gchange-client#54]
Bonjour, 
Je viens de faire un virement sur Gchange sur la clé indiqué dans le profil d'utilisateur... Sauf que cette clé de correspond à aucun compte ! Je me pose la question de l'utilité d'afficher la clé du compte gchange, je trouve que cela seme la confusion avec les comptes cesium, c'est déjà pas évident pour les non initiés ! 
Merci pour ton travail !

**Comment by blavenie** [comment]
J'ai modifié cette partie, dans la version 0.7.4 de cgahnge.
Maintenant, la clef interne a gchange n'est plus affichée.

L'utilisateur peut indiquer sa clef de paiement dans son profil. Celle-ci (si présente) est alors affichée.
