### ISSUE TITLE
Notifications email 

### ISSUE THREAD

**Issue by bablukid** [duniter-gchange/gchange-client#62]
J'ai raté des acheteurs car on ne reçoit rien par mail quand un acheteur potentiel poste un commentaire sur l'annonce ( ou qu'un message direct est envoyé ).

J'ai l'impression que c'est un cas courant, je suis tombé sur d'autres annonces avec des messages laissés sans réponse.

La communauté est encore petite , on peut donc recevoir des propositions plusieurs semaines, voire mois après avoir posté une annonce... et pour ma part j'avais oublié d'aller consulter gchange pour voir si j'avais des messages... 

Merci d'avoir fait gchange et bon courage pour la suite :-)

**Comment by blavenie** [comment]
Fixed v0.9.1
