### ISSUE TITLE
Seulement en Plein écran

### ISSUE THREAD

**Issue by Nyckelharpa** [duniter-gchange/gchange-client#65]
Bonjour Benoît,
Je viens de m'appercevoir (des mois après!!!) que je ne peux accéder à tous les boutons de Gchange qu'en mode "affichage Plein écran". Et c'est sans doute la même chose sur Césium et gAnnonce. Par exemple, je n'avais jamais vu ce bouton "à propos" qui me permet aujourd'hui de t'envoyer ce message. Je viens aussi de découvrir l'icone "envellope" où étaient accessibles mes notifications (ex des messages très anciens dont un de Anne Amblès). Je ne pouvais pas valider des annonces...
Peut-être est-ce dû à mon matériel? (Ubuntu 16-04 LTS, système 32 bits, Carte graphique NV98) Ou est-ce une question de configuration de votre coté?
Bonne fin d'été.
Bear'nard

**Comment by blavenie** [comment]
Fixed in 0.9.1 -  Add "message" on the left menu, on small screen.
