### ISSUE TITLE
Message d'erreur peu clair 

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [duniter-gchange/gchange-client#66]
J'ai essayé à plusieurs reprises de publier une annonce avec toujours ce message d'erreur : 

![image](https://user-images.githubusercontent.com/18427584/44996977-58453880-afab-11e8-9c7b-e24056a324c6.png)

Par essai/erreur, j'en ai conclu que ça devait être le poids des images uploadées qui était trop important. Si c'est vraiment le cas, il faudrait mettre un message d'erreur plus précis.

**Comment by blavenie** [comment]
closed in v0.9.1. This was due to image size
