### ISSUE TITLE
Libellés manquants à l'inscription

### ISSUE THREAD

**Issue by c-geek** [duniter-gchange/gchange-client#7]
Lors de la création de mon compte, je suis tombé sur 2 libellés non traduits : 

![image](https://user-images.githubusercontent.com/969136/28963575-e9db533a-7909-11e7-8f21-f81b2ae41f52.png)

![image](https://user-images.githubusercontent.com/969136/28963579-ece357b2-7909-11e7-906b-254e617d2878.png)

**Comment by blavenie** [comment]
@c-geek bizarre, je ne reproduis pas. Tu était dans la langue par défaut ?

**Comment by c-geek** [comment]
Je n'ai pas choisi de langue spécifiquement, je suis arrivé sur gchange directement, affiché en Français.

Dans les paramètres, cette langue est sélectionnée.

Bon, après je n'arrive plus à reproduire. Donc tu peux fermer si tu veux.
