### ISSUE TITLE
Édition du compte impossible

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [duniter-gchange/gchange-client#73]
Je ne suis pas en mesure d'éditer mon profil gchange car le champ "ville" indique "adresse inconnue". Similaire à #55 mais pas de contournement possible. Valable sur gchange.fr ainsi que test.gchange.fr

**Comment by blavenie** [comment]
Bonjour Hugo,

peux tu me donner ton nom de profile Gchange ?

**Comment by Hugo-Trentesaux** [comment]
J'avais oublié cette issue, mais je réessaye maintenant et le problème semble réglé : https://data.gchange.fr/user/profile/5tKdbNxGExhjRxHVBnykkS47W6aem6h3cx2hAJNdVDZW/_share
