### ISSUE TITLE
Mauvais champs « Nom, Prénom » à l'inscription

### ISSUE THREAD

**Issue by c-geek** [duniter-gchange/gchange-client#8]
Lors de mon inscription, j'ai saisi « Moreau, Cédric » dans le champ « Nom, Prénom ». Puis après création de mon compte, je tombe sur cette fiche récapitulative affichant à la place « Utilisateur 36U... » : 

![image](https://user-images.githubusercontent.com/969136/28963641-20b9229c-790a-11e7-973c-2b3635226cbc.png)

Si j'édite mon profil, je peux toutefois corriger et forcer la bonne valeur.

**Comment by c-geek** [comment]
Cas d'un autre utilisateur : 

![image](https://user-images.githubusercontent.com/969136/28965238-5e3f723c-7910-11e7-94b6-d4967129bcd6.png)

**Comment by blavenie** [comment]
@c-geek tu utilises la version web ou bien le desktop ?

**Comment by c-geek** [comment]
Version web.
