### ISSUE TITLE
Does it supports/displays other Duniter coins?

### ISSUE THREAD

**Issue by DaniellMesquita** [duniter-gchange/gchange-client#82]
@blavenie

**Comment by blavenie** [comment]
Oui, Gchange est générique :)
Il utilise, côté serveur, Cesium+ pod, qui fonctionne aussi bien su le G1-test que sur la G1
Et coté client, il reprend du code de Cesium, lui aussi générique.

Quel est ton besoin ?

**Comment by DaniellMesquita** [comment]
@blavenie
So, users can put items for sale using any Duniter coin?

Also, what are the ideal settings for a state (not country, but region/state)-wide Duniter coin?

**Comment by blavenie** [comment]
Not sure to understand what you need. Where are you leaving ?

**Comment by DaniellMesquita** [comment]
> Not sure to understand what you need. Where are you leaving ? Not in France ?

I'm not from France

**Comment by DaniellMesquita** [comment]
@blavenie
Why the server version haves 200 MB?

**Comment by DaniellMesquita** [comment]
@blavenie

**Comment by blavenie** [comment]
The change-pod can be run on another Duniter node, and then gchange App can request this pod, and display Ad using the new currency.
