### ISSUE TITLE
Emphase étrange dans la description

### ISSUE THREAD

**Issue by c-geek** [duniter-gchange/gchange-client#9]
Dans l'annonce https://www.gchange.fr/#/app/market/view/AV2sCk0HUFHiEK4L_opE/version-imprime-de-la-trm-pour-les-enfants, on peut voir un "@free" crée un lien vers https://www.gchange.fr/#/app/lookup/free.

![image](https://user-images.githubusercontent.com/969136/28963722-73f6f8da-790a-11e7-8ffa-85a5c713d3e1.png)

Cela semble être un petit bug d'analyse de motif, il me semble qu'il faudrait que le @ soit précédé soit de rien du tout (commencement de la chaîne de caractères), soit être précédé d'un espace ou d'un saut de ligne.

**Comment by blavenie** [comment]
Oui, d'ailleurs le pb est le même sur Cesium
