### ISSUE TITLE
etiquettes illisibles

### ISSUE THREAD

**Issue by katian** [duniter-gchange/gchange-client#93]
Bonjour,

certaines étiquettes sont illisibles, voir pièce jointe.
![etiquette](https://user-images.githubusercontent.com/1428843/67617556-7475eb80-f7e4-11e9-9517-25c7d48b07d1.jpg)

**Comment by blavenie** [comment]
Fix in v1.2. Add a small shadow behind the text 

Ajout d'une ombre portée

**Comment by katian** [comment]
> Fix in v1.2. Add a small shadow behind the text
> 
> Ajout d'une ombre portée

merci beaucoup Benoît
